### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by IIIdefconIII**
changes the support section

### CODE REVIEW

**Comment by IIIdefconIII** [comment]
card_mod:
  style: |
    ha-card {
    background: none !important;  
    border: none !important;
    }

**Comment by IIIdefconIII** [comment]
```
card_mod:
  style: |
    ha-card {
    background: none !important;  
    border: none !important;
    }
    ```

**Comment by MelleD** [comment]
I don't understand the point of the PR or the changes. 

A bit more context would be helpful. The changes don't look sensible

**Review by MelleD — CHANGES_REQUESTED** [review]
I don't understand the point of the PR or the changes. 

A bit more context would be helpful. The changes don't look sensible

**Comment by IIIdefconIII** [comment]
mybad i shoulpd have make a feature request instead

**Pull request closed without merging**
